baseURL = 'https://mohamed-aziz-ben-nessir.github.io/'
languageCode = 'en-us'
title = 'Mohamed Aziz Ben Nessir Blog'
theme ='hugo-PaperMod'
[params.homeInfoParams]
Title = "Hi there!"
Content = "My name is Mohamed Aziz, I'm a machine learning enthusiast and a developer. I enjoy writting technical blog posts, Here you can find articles about all things machine learning, web development and linux configuration. Hope you enjoy them!"
[[params.socialIcons]]
name = "Linkedin"
url="https://www.linkedin.com/in/mohamed-aziz-ben-nessir-9b517820a/"
[[params.socialIcons]]
name = "Github"
url="https://github.com/Mohamed-Aziz-Ben-Nessir"
[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20
